---
# -- Configure console plugins for OpenShift.
# @default -- ""
console_plugins:

  # -- Enable console plugin configuration.
  # @default -- false
  enabled: false

  # -- Optional: Syncwave for console plugin configuration.
  # @default -- 5
  syncwave: 5

  # -- List of console plugins to configure. Each list item will be added to the OpenShift UI.
  # @default -- empty
  plugins:
    - console-plugin-name

  # -- Optional: Namespace where kubernetes job shall be executed.
  # @default -- openshift-gitops
  job_namespace: kube-system

  # -- Optional: Name of the service account that will execute the Job.
  # @default -- enable-console-plugin-sa
  job_service_account: enable-console-plugin-sa

  # -- Optional: Name of the role that will be assigned to the service account.
  # @default -- enable-console-plugin-role
  job_service_account_role: enable-console-plugin-role

  # -- Optional: Name of the ClusterRoleBinding.
  # @default -- enable-console-plugin-crb
  job_service_account_crb: enable-console-plugin-crb

# -- Define operators that you want to deploy. A key/value setup is used here.
# Each new operator is a new key (in this example "my-operator")
# @default -- ""
operators:
  camelk-operator:
    # -- Enabled yes/no
    # @default -- false
    enabled: true

    # -- Syncwave for the operator deployment
    # @default -- 0
    syncwave: 0

    namespace:
      # -- The Namespace the Operator should be installed in.
      name: redhatcamelk

      # -- Description of the namespace.
      # @default -- ""
      descr: ""

      # -- Displayname of the namespace.
      # @default -- ""
      displayname:

      # -- Create the Namesoace yes/no.
      # @default -- false
      create: true

    # -- Definition of the Operator Subscription
    # @default -- ""
    subscription:
      # -- Channel of the Subscription
      # @default -- stable
      channel: 1.10.x

      # -- Update behavior of the Operator. Manual/Automatic
      # @default -- Automatic
      approval: Manual

      # -- Name of the Operator
      # @default -- "empty"
      operatorName: red-hat-camel-k

      # -- Source of the Operator
      # @default -- redhat-operators
      source: redhat-operators

      # -- Namespace of the source
      # @default -- openshift-marketplace
      sourceNamespace: openshift-marketplace
      csv: red-hat-camel-k-operator.v1.10.6


    operatorgroup:
      # -- Create an Operatorgroup object
      # @default -- false
      create: true

      # -- Monitor own Namespace. For some Operators no `targetNamespaces` must be defined
      # @default -- false
      notownnamespace: true
