---
# -- Define operators that you want to deploy. A key/value setup is used here.
# Each new operator is a new key (in this example "my-operator")
# @default -- ""
operators:
  camelk-operator:
    # -- Enabled yes/no
    # @default -- false
    enabled: true

    # -- Syncwave for the operator deployment
    # @default -- 0
    syncwave: 0

    namespace:
      # -- The Namespace the Operator should be installed in.
      name: redhatcamelk

      # -- Description of the namespace.
      # @default -- ""
      descr: ""

      # -- Displayname of the namespace.
      # @default -- ""
      displayname:

      # -- Create the Namesoace yes/no.
      # @default -- false
      create: true

    # -- Definition of the Operator Subscription
    # @default -- ""
    subscription:
      # -- Channel of the Subscription
      # @default -- stable
      channel: 1.10.x

      # -- Update behavior of the Operator. Manual/Automatic
      # @default -- Automatic
      approval: Manual

      # -- Name of the Operator
      # @default -- "empty"
      operatorName: red-hat-camel-k

      # -- Source of the Operator
      # @default -- redhat-operators
      source: redhat-operators

      # -- Namespace of the source
      # @default -- openshift-marketplace
      sourceNamespace: openshift-marketplace
      csv: red-hat-camel-k-operator.v1.10.6


    operatorgroup:
      # -- Create an Operatorgroup object
      # @default -- false
      create: true

      # -- Monitor own Namespace. For some Operators no `targetNamespaces` must be defined
      # @default -- false
      notownnamespace: true

   serviceAccount:
      # -- Name of the Service Account.
      name: "status-checker"
      create: true
